# fly.toml app configuration file generated for config-server on 2024-06-13T12:49:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'config-server'
primary_region = 'arn'

[build]

[env]
  SERVER_PORT=8080
  SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL = 'main'
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI = 'https://github.com/Lance-Uppercut/config-server-configs'
  SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS='{application}'
  SPRING_PROFILES_ACTIVE = 'git'
#  DEBUG='true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 512
